"""EOT claim document store + background generation (Proposal tab).

The claim is generated by AI from every project module, which takes too long for
an HTTP request — so generation runs in the background and the row's `status` is
polled by the UI. Blocking work runs in worker threads.

Generation is multi-pass: front matter and the contractual case, then one pass per
delay event, then the analysis and entitlement sections. A single call would cap
the report at one response's worth of output no matter how much evidence the data
room holds; a pass per event lets the claim grow with the record. Each completed
pass is written to the row, so the UI renders the claim as it is assembled rather
than showing a spinner for several minutes.
"""
import asyncio
import os
from datetime import datetime, timezone
from typing import Dict, List, Optional

import anthropic

from app.db import SessionLocal
from app.models import EOTClaim
from app.services import (
    admissibility_service,
    delay_event_service,
    document_service,
    methodology_service,
    project_clause_service,
    project_query_service,
    project_service,
)
from app.services.ai_service import (
    MODEL,
    build_claim_context,
    generate_claim_analysis,
    generate_claim_delay_event,
    generate_claim_front_matter,
)

# Delay events are drafted concurrently; the cap keeps one large claim from
# saturating the account's rate limit and starving other projects.
_EVENT_CONCURRENCY = int(os.getenv("CLAIM_EVENT_CONCURRENCY", "4"))

_sem = asyncio.Semaphore(int(os.getenv("CLAIM_CONCURRENCY", "2")))

_NOT_CONFIGURED = (
    "AI analysis is not configured — set ANTHROPIC_API_KEY in apps/backend/.env "
    "and restart the backend."
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def get_claim(project_id: str) -> Dict:
    """Return the stored claim + status for a project (idle shape if none yet)."""
    with SessionLocal() as db:
        row = db.get(EOTClaim, project_id)
        return row.to_dict() if row else {
            "projectId": project_id, "content": None, "model": None,
            "status": "", "error": None, "updatedAt": None,
        }


def _set(project_id: str, **fields) -> None:
    with SessionLocal() as db:
        row = db.get(EOTClaim, project_id)
        if not row:
            row = EOTClaim(projectId=project_id, createdAt=_now())
            db.add(row)
        for k, v in fields.items():
            setattr(row, k, v)
        row.updatedAt = _now()
        db.commit()


def mark_running(project_id: str) -> None:
    _set(project_id, status="running", error=None)


def _load(project_id: str) -> Dict:
    """Blocking: gather every project module the claim is written from (run in a
    thread). The report draws on the same data the workspace tabs show — delay
    events, the Clause Library, admissibility, methodology, queries and the data
    room — so a section is only thin when the underlying tab is."""
    return {
        "project": project_service.get_project(project_id),
        "events": delay_event_service.list_by_project(project_id),
        "documents": document_service.list_by_project(project_id),
        "clauses": project_clause_service.list_by_project(project_id),
        "queries": project_query_service.list_by_project(project_id),
        # Stored assessments keep their status envelope; the claim only needs the
        # analyst-reviewed content.
        "admissibility": (admissibility_service.get(project_id) or {}).get("content"),
        "methodology": methodology_service.get_assessment(project_id),
    }


def _delay_events_section(sections: List[Dict]) -> Optional[Dict]:
    """Locate the section the per-event subsections belong under.

    Matched by number first, then by heading, then by position — the model is told
    to emit section 5 last, so a drifted number still lands correctly.
    """
    for s in sections:
        if (s.get("number") or "").strip() == "5":
            return s
    for s in sections:
        if "DELAY EVENT" in (s.get("heading") or "").upper():
            return s
    return sections[-1] if sections else None


def _renumber(sections: List[Dict]) -> List[Dict]:
    """Force sequential section and subsection numbering.

    The passes are drafted independently, so their numbering is only as consistent
    as the model's arithmetic. Numbering here instead means the contents page and
    every cross-reference agree with the body. Part labels (A, B, C…) are the
    delay-event template's own and are left alone.
    """
    for i, section in enumerate(sections, start=1):
        section["number"] = str(i)
        for j, sub in enumerate(section.get("subsections") or [], start=1):
            sub["number"] = f"{i}.{j}"
    return sections


def _assemble(
    front: Dict, event_subs: List[Optional[Dict]], analysis: Optional[Dict]
) -> Dict:
    """Splice the passes into one claim document.

    Safe to call while passes are still running — unfinished events are simply
    absent, which is what lets the UI render the claim as it builds.
    """
    sections = [dict(s) for s in (front.get("sections") or [])]
    target = _delay_events_section(sections)
    if target is not None:
        subs = list(target.get("subsections") or [])
        for sub in event_subs:
            if sub:
                subs.append(
                    {
                        "number": "",  # assigned by _renumber
                        "heading": sub.get("heading", ""),
                        "blocks": sub.get("blocks") or [],
                        "parts": sub.get("parts") or [],
                    }
                )
        target["subsections"] = subs

    if analysis:
        sections.extend(dict(s) for s in (analysis.get("sections") or []))

    return {
        "title": front.get("title") or "Extension of Time Claim",
        "reference": front.get("reference") or "",
        "sections": _renumber(sections),
    }


async def run_generation(project_id: str) -> None:
    """Generate the EOT claim in the background and store it, pass by pass."""
    async with _sem:
        _set(project_id, status="running", error=None)
        try:
            if not os.getenv("ANTHROPIC_API_KEY"):
                _set(project_id, status="failed", error=_NOT_CONFIGURED)
                return
            data = await asyncio.to_thread(_load, project_id)
            if not data.get("project"):
                _set(project_id, status="failed", error="Project not found.")
                return

            context = build_claim_context(**data)
            events = data.get("events") or []

            # Serialise the progress writes: several event passes finish at once and
            # SQLite will not take concurrent writers on the same row.
            write_lock = asyncio.Lock()

            async def publish(content: Dict) -> None:
                async with write_lock:
                    await asyncio.to_thread(
                        _set, project_id, content=content, model=MODEL, status="running"
                    )

            # Pass 1 — front matter and the contractual case.
            front = await generate_claim_front_matter(context)
            event_subs: List[Optional[Dict]] = [None] * len(events)
            await publish(_assemble(front, event_subs, None))

            # Pass 2 — one draft per delay event, bounded concurrency.
            if events:
                gate = asyncio.Semaphore(_EVENT_CONCURRENCY)

                async def draft(index: int, event: Dict) -> None:
                    async with gate:
                        event_subs[index] = await generate_claim_delay_event(
                            context, event
                        )
                    await publish(_assemble(front, event_subs, None))

                await asyncio.gather(
                    *(draft(i, e) for i, e in enumerate(events))
                )

            # Pass 3 — analysis, entitlement and attachments.
            headings = [s.get("heading", "") for s in event_subs if s]
            analysis = await generate_claim_analysis(context, headings)

            _set(
                project_id,
                content=_assemble(front, event_subs, analysis),
                model=MODEL,
                status="done",
                error=None,
            )
        except anthropic.AuthenticationError:
            _set(project_id, status="failed", error=_NOT_CONFIGURED)
        except anthropic.APIStatusError as e:
            # Carry the provider's own message through: a bare status code turns a
            # one-line diagnosis ("compiled grammar is too large") into a hunt.
            detail = (getattr(e, "message", "") or str(e)).strip()
            _set(
                project_id,
                status="failed",
                error=f"AI provider error ({e.status_code}): {detail}"[:500],
            )
        except Exception as e:  # noqa: BLE001
            _set(project_id, status="failed", error=f"{type(e).__name__}: {e}"[:500])
